spring:
  # 数据源配置
  datasource:
    name: test
    url: jdbc:sqlserver://localhost:1433;DatabaseName=my_app
    username: sa
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    filters: stat, wall
    max-active: 20
    initial-size: 1
    max-wait: 60000
    min-idle: 1
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: select 'x'
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-open-prepared-statements: 20

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

shiro:
  cors:
    tokenHeaderName: Authorization
    clientHostPortName: XForwardedFor
    accessControlAllowMethods: POST, GET, PUT, DELETE,OPTIONS
    accessControlAllowHeaders: Authentication, Origin, X-Requested-With, Content-Type, token,Accept, Authorization, XForwardedFor
    accessControlMaxAge: 3600
    accessControlAllowOrigin: http://localhost:8082,http://localhost:8080

#2592000   30天

  url:
    login: /login
    forbidden: /forbidden
    logout: /logout
    unLogin: /unLogin
    index: /index
    unAuthorized: /403

mybatis:
  config:
    # Mybatis model 路径
    typeAliasesPackage: tk.mapper.model,com.tokid.model
    reasonable: true
    supportMethodsArguments: true
    returnPageInfo: check
    params: count=countSql
    # Mybatis mapper xml 路径
    mapperLocations: classpath:mapper/*.xml
    # Mybatis mapper interface 路径
    basePackage: com.tokid.mapper
    # 通用 mapper 接口
    mappers: tk.mybatis.mapper.common.Mapper
    # 主键自增全局配置
    identity: MYSQL
    logImpl: STDOUT_LOGGING

logging:
  level:
    org.springframework.web: ERROR
    com.yiibai: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: logs/mylog.log